version: "3.8"
services:
  db:
    env_file:
      - dev.env
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
    - pg_data:/var/lib/postgresql/data

  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    env_file:
      - ./dev.env
    ports:
    - 5000:5000
    volumes:
      - ./services/web/:/app/

volumes:
  pg_data: